/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    colors: {
      transparent: "transparent",
      black: "rgb(var(--color-black) / <alpha-value>)",
      white: "rgb(var(--color-white) / <alpha-value>)",
      header: "rgb(var(--color-header) / <alpha-value>)",
      "header-combi": "rgb(var(--color-header-combi) / <alpha-value>)",
      navbar: "rgb(var(--color-navbar) / <alpha-value>)",
      "navbar-combi": "rgb(var(--color-navbar-combi) / <alpha-value>)",
      "button-primary": "rgb(var(--color-button-primary) / <alpha-value>)",
      "button-primary-combi":
        "rgb(var(--color-button-primary-combi) / <alpha-value>)",
      "button-secondary": "rgb(var(--color-button-secondary) / <alpha-value>)",
      "button-secondary-combi":
        "rgb(var(--color-button-secondary-combi) / <alpha-value>)",
      highlight: "rgb(var(--color-highlight) / <alpha-value>)",
      text: "rgb(var(--color-text) / <alpha-value>)",
      kasasi: {
        blue: "rgb(var(--color-kasasi-blue) / <alpha-value>)",
        red: "rgb(var(--color-kasasi-red) / <alpha-value>)",
        "blue-light": "rgb(var(--color-kasasi-blue-light) / <alpha-value>)",
        green: "rgb(var(--color-kasasi-green) / <alpha-value>)",
      },
      function: {
        red: "rgb(var(--color-function-red) / <alpha-value>)",
        orange: "rgb(var(--color-function-orange) / <alpha-value>)",
        green: "rgb(var(--color-function-green) / <alpha-value>)",
        cyan: "rgb(var(--color-function-cyan) / <alpha-value>)",
        purple: "rgb(var(--color-function-purple) / <alpha-value>)",
        "blue-light": "rgb(var(--color-function-blue-light) / <alpha-value>)",
      },
      gray: {
        100: "rgb(var(--color-gray-100) / <alpha-value>)",
        200: "rgb(var(--color-gray-200) / <alpha-value>)",
        300: "rgb(var(--color-gray-300) / <alpha-value>)",
        400: "rgb(var(--color-gray-400) / <alpha-value>)",
        500: "rgb(var(--color-gray-500) / <alpha-value>)",
        600: "rgb(var(--color-gray-600) / <alpha-value>)",
        700: "rgb(var(--color-gray-700) / <alpha-value>)",
        800: "rgb(var(--color-gray-800) / <alpha-value>)",
      },
    },
    spacing: {
      px: "1px",
      0: "0",
      1: "0.4rem",
      2: "0.8rem",
      3: "1.2rem",
      4: "1.6rem",
      5: "2rem",
      6: "2.4rem",
      7: "2.8rem",
      8: "3.2rem",
      9: "3.6rem",
      10: "4.0rem",
      11: "4.4rem",
      12: "4.8rem",
      16: "6.4rem",
      20: "8.0rem",
      24: "9.6rem",
      28: "11.2rem",
      32: "12.8rem",
      36: "14.4rem",
      40: "16.0rem",
      44: "17.6rem",
      48: "19.2rem",
      52: "20.8rem",
      56: "22.4rem",
      60: "24.0rem",
      64: "25.6rem",
      72: "28.8rem",
      80: "32rem",
      96: "38.4rem",
      112: "44.8rem",
      128: "51.2rem",
      144: "57.6rem",
      168: "67.2rem",
      192: "76.8rem",
      256: "102.4rem",
      384: "153.6rem",
      512: "204.8rem",
      640: "256rem",
      768: "307.2rem",
    },
    borderRadius: {
      none: "0",
      sm: "0.2rem",
      DEFAULT: "0.4rem",
      md: "0.6rem",
      lg: "0.8rem",
      full: "9999px",
    },
    fontFamily: {
      sans: ["Open Sans", "sans-serif"],
    },
    fontSize: {
      xs: "0.9rem",
      sm: "1.2rem",
      md: "1.3rem",
      base: "1.4rem",
      lg: "1.6rem",
      xl: "1.8rem",
      "2xl": "2rem",
      "3xl": "3.2rem",
      "4xl": "4.2rem",
      "5xl": "5.4rem",
      "6xl": "6.6rem",
    },
    maxWidth: {
      xs: "32rem",
      sm: "38.4rem",
      md: "44.8rem",
      lg: "51.2rem",
      xl: "57.6rem",
      "2xl": "67.2rem",
      "3xl": "76.8rem",
      "4xl": "89.6rem",
      "5xl": "102.4rem",
      "6xl": "115.2rem",
      "1/5": "20%",
      "1/4": "25%",
      "1/3": "33%",
      "2/5": "40%",
      "1/2": "50%",
      "3/5": "60%",
      "2/3": "66%",
      "3/4": "75%",
      "4/5": "80%",
      full: "100%",
    },
    zIndex: {
      0: 0,
      1: 1,
      2: 2,
      3: 3,
      4: 4,
      5: 5,
      10: 10,
      20: 20,
      30: 30,
      40: 40,
      50: 50,
      auto: "auto",
    },
    extend: {
      fill: (theme) => theme("colors"),
      minWidth: (theme) => theme("spacing"),
      maxWidth: (theme) => theme("spacing"),
      minHeight: (theme) => theme("spacing"),
      maxHeight: (theme) => theme("spacing"),
      inset: {
        "1/5": "20%",
        "1/4": "25%",
        "1/3": "33%",
        "2/5": "40%",
        "1/2": "50%",
        "3/5": "60%",
        "2/3": "66%",
        "3/4": "75%",
        "4/5": "80%",
      },
      scale: {
        120: "1.2",
      },
      transitionDuration: {
        400: "400ms",
      },
      borderColor: (theme) => ({
        DEFAULT: theme("colors.gray.300"),
      }),
      backgroundImage: {
        "lighten-sm":
          "linear-gradient(rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.1))",
        "lighten-md":
          "linear-gradient(rgba(255, 255, 255, 0.2), rgba(255, 255, 255, 0.2))",
        "lighten-lg":
          "linear-gradient(rgba(255, 255, 255, 0.3), rgba(255, 255, 255, 0.3))",
        "darken-sm": "linear-gradient(rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.1))",
        "darken-md": "linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2))",
        "darken-lg": "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3))",
      },
    },
  },
};
